export const MOCK_TRAFFIC = {
    domain: 'firecrawl.dev',
    source: {
        url: 'https://www.semrush.com/analytics/overview/?q=firecrawl.dev&searchType=domain',
        name: 'semrush',
        method: 'rpc',
    },
    traffic: {
        semrushRank: 76133,
        totalTraffic: 27348,
        adwordsTraffic: 3015,
        organicTraffic: 24333,
        adwordsPositions: 179,
        organicPositions: 10740,
        adwordsTrafficCost: 13192,
        organicTrafficCost: 105185,
        organicTrafficBranded: 17414,
        organicTrafficNonBranded: 6919,
    },
    dbStatus: 'created',
    aiSources: {
        sources: [
            { domain: 'medium.com', mentions_count: 165 },
            { domain: 'youtube.com', mentions_count: 149 },
            { domain: 'scrapingbee.com', mentions_count: 143 },
            { domain: 'reddit.com', mentions_count: 128 },
            { domain: 'brightdata.com', mentions_count: 127 },
        ],
    },
    authority: {
        backlinks: 71276,
        linkPower: 4.85,
        naturalness: 5,
        domainHealth: 44,
        authorityScore: 42,
        referringDomains: 4612,
    },
    aiOverview: { citedPages: 659, visibility: 22 },
    competitors: [
        {
            domain: 'webscraper.io',
            traffic: 194978,
            positions: 5216,
            trafficCost: 768163,
            commonKeywords: 604,
            competitionLvl: 0.29,
            organicTraffic: 80451,
            adwordsPositions: 0,
            organicPositions: 5030,
            organicTrafficCost: 320468,
            serpFeaturesTraffic: 114527,
            serpFeaturesPositions: 186,
            serpFeaturesTrafficCost: 447695,
        },
        {
            domain: 'octoparse.com',
            traffic: 26102,
            positions: 12865,
            trafficCost: 61185,
            commonKeywords: 661,
            competitionLvl: 0.23,
            organicTraffic: 23689,
            adwordsPositions: 63,
            organicPositions: 10224,
            organicTrafficCost: 55182,
            serpFeaturesTraffic: 2413,
            serpFeaturesPositions: 2641,
            serpFeaturesTrafficCost: 6003,
        },
        {
            domain: 'browse.ai',
            traffic: 16131,
            positions: 7477,
            trafficCost: 43978,
            commonKeywords: 466,
            competitionLvl: 0.23,
            organicTraffic: 15470,
            adwordsPositions: 92,
            organicPositions: 7322,
            organicTrafficCost: 43497,
            serpFeaturesTraffic: 661,
            serpFeaturesPositions: 155,
            serpFeaturesTrafficCost: 481,
        },
        {
            domain: 'zyte.com',
            traffic: 23414,
            positions: 4594,
            trafficCost: 87816,
            commonKeywords: 439,
            competitionLvl: 0.21,
            organicTraffic: 22300,
            adwordsPositions: 604,
            organicPositions: 3737,
            organicTrafficCost: 84635,
            serpFeaturesTraffic: 1114,
            serpFeaturesPositions: 857,
            serpFeaturesTrafficCost: 3181,
        },
        {
            domain: 'scrapy.org',
            traffic: 13991,
            positions: 3452,
            trafficCost: 45037,
            commonKeywords: 387,
            competitionLvl: 0.2,
            organicTraffic: 13974,
            adwordsPositions: 0,
            organicPositions: 3412,
            organicTrafficCost: 45003,
            serpFeaturesTraffic: 17,
            serpFeaturesPositions: 40,
            serpFeaturesTrafficCost: 34,
        },
        {
            domain: 'firecrawl.dev',
            traffic: 25893,
            positions: 11402,
            trafficCost: 107842,
            commonKeywords: 11402,
            competitionLvl: 1,
            organicTraffic: 24333,
            adwordsPositions: 179,
            organicPositions: 10740,
            organicTrafficCost: 105185,
            serpFeaturesTraffic: 1560,
            serpFeaturesPositions: 662,
            serpFeaturesTrafficCost: 2657,
        },
    ],
};
